import { Asset, Document, Reminder, UserProfile } from './types';

export const INITIAL_USER_PROFILE: UserProfile = {
  name: 'Shobhit Poddar',
  email: 'shobhitpoddar410@gmail.com',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=120&q=80',
  tier: 'premium',
  storageUsed: '42.8 MB',
  storageLimit: 'Unlimited',
  organizationScore: 78, // starts at 78, can go up/down as they fill out profiles
};

export const INITIAL_DOCUMENTS: Document[] = [
  {
    id: 'doc_1',
    name: 'MacBook Pro Purchase Invoice.pdf',
    type: 'invoice',
    uploadDate: '2025-01-15',
    fileSize: '1.2 MB',
    fileUrl: '#',
    tags: ['#Electronics', '#Tax2025', '#Receipt'],
    assetId: 'ast_1',
    ocrContent: 'APPLE INDIA PVT LTD. Invoice #INV-94024871. Sold to: Shobhit Poddar. Apple MacBook Pro 16" M4 Max, 32GB RAM, 1TB SSD. Total Paid: ₹2,30,000. Date: 2025-01-15.',
  },
  {
    id: 'doc_2',
    name: 'OLED TV Extended Warranty Policy.pdf',
    type: 'warranty',
    uploadDate: '2025-02-12',
    fileSize: '840 KB',
    fileUrl: '#',
    tags: ['#Sony', '#TV', '#Warranty'],
    assetId: 'ast_2',
    ocrContent: 'SONY ACCIDENT PROTECTION COVERAGE. Policy Number: SEC-4810247. Covered Asset: Sony Bravia OLED XR 55" TV. valid dates: 2025-02-12 to 2028-02-11. Provider: Sony India Care.',
  },
  {
    id: 'doc_3',
    name: 'Home Insurance Policy Certificate.pdf',
    type: 'insurance',
    uploadDate: '2026-06-01',
    fileSize: '3.4 MB',
    fileUrl: '#',
    tags: ['#HomeInsurance', '#Important', '#ICICI'],
    ocrContent: 'ICICI LOMBARD PRIVATE ASSETS PROTECTION DEED. Policy: H-49204-INS. Insured Location: Flat 402, Oakwood Towers. Cover Amount: ₹45,00,000. Annual Premium: ₹18,500.',
  },
  {
    id: 'doc_4',
    name: 'Dyson Airwrap User Manual.pdf',
    type: 'manual',
    uploadDate: '2025-03-20',
    fileSize: '12.5 MB',
    fileUrl: '#',
    tags: ['#Dyson', '#Manual', '#Styling'],
    assetId: 'ast_3',
    ocrContent: 'DYSON AIRWRAP MULTI-STYLER MANUAL. Model HS05. Cleaning Instructions: Wash filter monthly. Register within 30 days for 2-year warranty support.',
  },
  {
    id: 'doc_5',
    name: 'IKEA Table Assembly Guide.pdf',
    type: 'manual',
    uploadDate: '2025-06-05',
    fileSize: '4.8 MB',
    fileUrl: '#',
    tags: ['#IKEA', '#Furniture', '#Setup'],
    assetId: 'ast_4',
  },
  {
    id: 'doc_6',
    name: 'Refrigerator Bill.jpg',
    type: 'receipt',
    uploadDate: '2024-11-20',
    fileSize: '650 KB',
    fileUrl: '#',
    tags: ['#Samsung', '#Appliance', '#Receipt'],
    assetId: 'ast_5',
  },
  {
    id: 'doc_7',
    name: 'Apartment Registration Deed.pdf',
    type: 'certificate',
    uploadDate: '2023-08-14',
    fileSize: '15.2 MB',
    fileUrl: '#',
    tags: ['#Property', '#Legal', '#Vault'],
  },
];

// Seed standard pre-existing assets (the user's starting portfolio)
export const INITIAL_ASSETS: Asset[] = [
  {
    id: 'ast_1',
    name: 'MacBook Pro 16" (M4 Max)',
    brand: 'Apple',
    modelNumber: 'A3184',
    serialNumber: 'C02LN49RFQQY',
    description: 'Workspace laptop with 32GB RAM and 1TB SSD. Peak computing power used for development & design.',
    category: 'electronics',
    purchaseDate: '2025-01-15',
    purchasePrice: 230000,
    currentValue: 195500, // depreciated after ~1.5 years
    depreciationRate: 15,
    store: 'Apple Store, BKC',
    warrantyProvider: 'AppleCare+',
    warrantyExpiry: '2028-01-14',
    warrantyActive: true,
    room: 'Study Room',
    storageLocation: 'Main Desk',
    tags: ['#Workstation', '#Apple', '#HighValue', '#Insured'],
    imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=400&q=80',
    documentIds: ['doc_1'],
    notes: 'Covered under premium AppleCare+ protection with spill cover until 2028.',
    completionRate: 100,
    maintenanceStreak: 3,
    createdAt: '2025-01-15T10:00:00Z',
  },
  {
    id: 'ast_2',
    name: 'Sony Bravia UltraHD OLED 55"',
    brand: 'Sony',
    modelNumber: 'XR-55A80K',
    serialNumber: 'SY-84021948',
    description: 'Immersive entertainment console with cognitive processor XR and acoustic surface audio.',
    category: 'electronics',
    purchaseDate: '2025-02-12',
    purchasePrice: 165000,
    currentValue: 132000,
    depreciationRate: 20,
    store: 'Sony Center, BKC',
    warrantyProvider: 'Sony Premium Protect',
    warrantyExpiry: '2028-02-11',
    warrantyActive: true,
    room: 'Living Room',
    storageLocation: 'Media Console Wall',
    tags: ['#Media', '#Sony', '#OLED'],
    imageUrl: 'https://images.unsplash.com/photo-1593305841991-05c297ba4575?auto=format&fit=crop&w=400&q=80',
    documentIds: ['doc_2'],
    notes: 'Fitted on low-profile custom wall mount.',
    completionRate: 90,
    maintenanceStreak: 1,
    createdAt: '2025-02-12T10:00:00Z',
  },
  {
    id: 'ast_3',
    name: 'Dyson Airwrap Complete Multi-Styler',
    brand: 'Dyson',
    modelNumber: 'HS05',
    serialNumber: 'DY-0248197A',
    description: 'Special edition styling bundle using Coanda airflow technology for zero heat damage.',
    category: 'appliances',
    purchaseDate: '2025-03-20',
    purchasePrice: 48900,
    currentValue: 44000,
    depreciationRate: 10,
    store: 'Dyson Demo Store, BKC',
    warrantyProvider: 'Dyson India Care',
    warrantyExpiry: '2027-03-19',
    warrantyActive: true,
    room: 'Bedroom',
    storageLocation: 'Dresser Drawer 2',
    tags: ['#Styling', '#Dyson', '#Appliance'],
    imageUrl: 'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&w=400&q=80',
    documentIds: ['doc_4'],
    notes: 'Wash the filter attachment once a month to avoid suction blockages.',
    completionRate: 95,
    maintenanceStreak: 4,
    createdAt: '2025-03-20T10:00:00Z',
  },
  {
    id: 'ast_4',
    name: 'Bekant Ergonomic Standing Desk',
    brand: 'IKEA',
    modelNumber: 'IK-590.222',
    serialNumber: 'IK-94024812',
    description: 'Sit-stand desk with electrical height adjustment from 65 to 125cm. Finished in white oak.',
    category: 'furniture',
    purchaseDate: '2025-06-05',
    purchasePrice: 38000,
    currentValue: 34200,
    depreciationRate: 10,
    store: 'IKEA, Navi Mumbai',
    warrantyProvider: 'IKEA 10-Year Guarantee',
    warrantyExpiry: '2035-06-04',
    warrantyActive: true,
    room: 'Study Room',
    storageLocation: 'North Window Corner',
    tags: ['#Workstation', '#IKEA', '#StandingDesk'],
    imageUrl: 'https://images.unsplash.com/photo-1530018607912-eff2df114f11?auto=format&fit=crop&w=400&q=80',
    documentIds: ['doc_5'],
    notes: 'Max load is 150 lbs.',
    completionRate: 85,
    createdAt: '2025-06-05T10:00:00Z',
  },
  {
    id: 'ast_5',
    name: 'Smart Triple-Door Refrigerator 450L',
    brand: 'Samsung',
    modelNumber: 'RF45-S',
    serialNumber: 'SA-94017AA7',
    description: 'French door refrigerator featuring Twin Cooling Plus, digital inverter compass, and smart diagnostics.',
    category: 'appliances',
    purchaseDate: '2024-11-20',
    purchasePrice: 115000,
    currentValue: 86250,
    depreciationRate: 25,
    store: 'Reliance Digital',
    warrantyProvider: 'Samsung 20Y Digital Inverter Protection',
    warrantyExpiry: '2044-11-19',
    warrantyActive: true,
    room: 'Kitchen',
    storageLocation: 'Fridge Enclosure Corner',
    tags: ['#SmartHome', '#Kitchen', '#Samsung'],
    imageUrl: 'https://images.unsplash.com/photo-1571175352279-880050853b1b?auto=format&fit=crop&w=400&q=80',
    documentIds: ['doc_6'],
    notes: 'Warranty is for 1 year comprehensive, 20 years on compressor.',
    completionRate: 100,
    maintenanceStreak: 2,
    createdAt: '2024-11-20T10:00:00Z',
  },
  {
    id: 'ast_6',
    name: 'Land Registry Deed & Title Flat 402',
    brand: 'Government Authorities',
    modelNumber: 'REG-2023-402',
    serialNumber: 'DL3C-4092-23',
    description: 'Primary legal ownership certificate of the flat registered with the local state sub-registrar office.',
    category: 'documents',
    purchaseDate: '2023-08-14',
    purchasePrice: 1200000, // Crucial for reflecting the estimated value
    currentValue: 1350000, // appreciated asset!
    depreciationRate: -10, // negative depreciation (appreciation)
    store: 'State Lands Registrar Office',
    warrantyProvider: 'State Property Insurance',
    warrantyExpiry: '2043-08-13',
    warrantyActive: true,
    room: 'Study Room',
    storageLocation: 'Fireproof Physical Safe',
    tags: ['#Property', '#Deed', '#ExtremelyImportant'],
    imageUrl: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=400&q=80',
    documentIds: ['doc_7'],
    notes: 'Keep physical copies in safe at all times.',
    completionRate: 100,
    createdAt: '2023-08-14T10:00:00Z',
  },
  {
    id: 'ast_7',
    name: 'Superlight Carbon Road Bike (Emonda SL5)',
    brand: 'Trek',
    modelNumber: 'SL5-2025',
    serialNumber: 'TK-124890214',
    description: 'High-performance carbon road bike fitted with Shimano 105 groupset and Bontrager rims.',
    category: 'assets',
    purchaseDate: '2025-05-18',
    purchasePrice: 285000,
    currentValue: 242250,
    depreciationRate: 15,
    store: 'Trek Concept Store, Mumbai',
    warrantyProvider: 'Trek Lifetime Frame Support',
    warrantyExpiry: '2099-12-31',
    warrantyActive: true,
    room: 'Garage',
    storageLocation: 'Wall Mount Bike Rack 1',
    tags: ['#Cycling', '#Sports', '#CarbonFiber', '#Valuable'],
    imageUrl: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=400&q=80',
    completionRate: 80,
    createdAt: '2025-05-18T10:00:00Z',
  }
];

export const INITIAL_REMINDERS: Reminder[] = [
  {
    id: 'rem_1',
    title: 'Living Room TV Insurance renewal',
    type: 'insurance',
    date: '2026-07-15',
    assetId: 'ast_2',
    assetName: 'Sony Bravia UltraHD OLED 55"',
    completed: false,
  },
  {
    id: 'rem_2',
    title: 'Water Purifier Filter replacement service',
    type: 'service',
    date: '2026-06-25', // soon!
    assetName: 'Living Room Water Purifier',
    completed: false,
  },
  {
    id: 'rem_3',
    title: 'Study standing desk warranty check',
    type: 'warranty',
    date: '2026-08-01',
    assetId: 'ast_4',
    assetName: 'Bekant Ergonomic Standing Desk',
    completed: false,
  },
  {
    id: 'rem_4',
    title: 'Upload registration invoice for Dyson multi-styler',
    type: 'document',
    date: '2026-06-29',
    assetId: 'ast_3',
    assetName: 'Dyson Airwrap Complete Multi-Styler',
    completed: false,
  }
];

export const CORRELATION_MOCKS = {
  electronics: { count: 23, total: 475000 },
  furniture: { count: 17, total: 185000 },
  appliances: { count: 12, total: 165000 },
  documents: { count: 36, total: 1350000 }, // property asset price inside document deed
  assets: { count: 14, total: 382000 },
  household: { count: 26, total: 68000 }
};

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'log_1',
    title: 'Asset Added Successfully',
    description: 'Sony Bravia TV added to Living Room',
    timestamp: 'Just now',
    icon: 'Tv',
    type: 'create',
  },
  {
    id: 'log_2',
    title: 'Receipt Scanned & Autofilled',
    description: 'Dyson Airwrap receipt parsed via Gemini Deep Scan',
    timestamp: '2 hours ago',
    icon: 'Scan',
    type: 'document',
  },
  {
    id: 'log_3',
    title: 'Maintenance Log Updated',
    description: 'Registered annual standing desk leg alignment checkup',
    timestamp: 'Yesterday',
    icon: 'CheckSquare',
    type: 'maintenance',
  },
  {
    id: 'log_4',
    title: 'Document Transferred',
    description: 'Land Registry Deed linked to physical fireproof safe storage',
    timestamp: '5 days ago',
    icon: 'FileText',
    type: 'document',
  }
];
